services:
  auth_server:
    container_name: bank_app_auth_server
    restart: always
    image: dudge1/bank_app_auth_server:latest
    ports:
      - "3500:3500"
    environment:
      NODE_ENV: development
      AUTH_PORT: 3500
      DB_URI: mongodb+srv://dudge1:ip3bank@bank-app-ip3.yodwqq8.mongodb.net/IP3DB?retryWrites=true&w=majority&appName=Bank-App-IP3
    depends_on:
      - mongo

  express_server:
    container_name: bank_app_express_server
    restart: always
    image: dudge1/bank_app_express_server:latest
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: development
      SERVER_PORT: 5001
      DB_URI: mongodb+srv://dudge1:ip3bank@bank-app-ip3.yodwqq8.mongodb.net/IP3DB?retryWrites=true&w=majority&appName=Bank-App-IP3
    depends_on:
      - mongo

  mongo:
    container_name: mongodb_bank_app
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb:
